### ISSUE TITLE
Checklist for doing in Hacking days

### ISSUE THREAD

**Issue by bs1phc** [Cov-ComSec/Cov-ComSec.github.io#3]
We can do tracks on hackthebox
or
https://blog.tryhackme.com/going-from-zero-to-hero/
![image.png](https://app.gitkraken.com/api/glo/boards/5f96de4b0d832b0011208b6c/attachments/5f99f5a66ddf5200112fd9de)

**Comment by jackorcherton** [comment]
Maybe - always try to link to a box on THM every week for extra challenges (see Go Further Sections on the website) or see presentations

**Comment by bs1phc** [comment]
yup or we can create like a guide or some sort of how to get into hacking

**Comment by jackorcherton** [comment]
Would say that was pretty well covered in week 3 by Ziemni
